---
title: "Assignment 3"
author: "Anthony Luna"
date: "2/24/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
knitr::opts_chunk$set(echo = TRUE)
source(here("R","ricker.R"))
source(here("R","ricker_outcome.R"))
```
# Example usage of the `ricker` and `ricker_outcome` functions

```{r}
w_1 <- ricker(A0=5,
            J0=5,
            u=.2,
            y0=10,
            a=5,
            b=5,
            c11=0.1,
            c22=0.1,
            c12=0.11,
            c21=0.12)

```

```
ricker_outcome(w,species_x_name = "Giraffe",species_y_name = 2)
# Not Run
Error in ricker_outcome(w, species_x_name = "giraffe", species_y_name = 2) : Assertion on 'species_y_name' failed: Must be of type 'string', not 'double'.
```
```{r}
ricker_outcome(w_1,species_x_name = "Giraffe",species_y_name = "Elephant")
```

```{r}
w_2 <- ricker(A0=10,
            J0=10,
            u=.2,
            y0=10,
            a=5,
            b=5,
            c11=0.1,
            c22=0.1,
            c12=0.11,
            c21=0.12)

```

```{r}
ricker_outcome(w_2,species_x_name = "Giraffe",species_y_name = "Elephant")
```


```{r}
w_3 <- ricker(A0=10,
            J0=10,
            u=.2,
            y0=20,
            a=5,
            b=5,
            c11=0.1,
            c22=0.1,
            c12=0.11,
            c21=0.12)

```

```{r}

ricker_outcome(w_3,species_x_name = "Giraffe",species_y_name = "Elephant")


```







```{r}
w_4 <- ricker(A0=10,
            J0=10,
            u=.2,
            y0=20,
            a=5,
            b=5,
            c11=2.1,
            c22=3.1,
            c12=0.11,
            c21=0.12)

```

```{r}

ricker_outcome(w_4,species_x_name = "Giraffe",species_y_name = "Elephant")


```